// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7eCXxswvjUWyd6tVvgoT8tLt8xsXQPhE',
    appId: '1:812438153804:web:b37d73b1563e6f29a822e9',
    messagingSenderId: '812438153804',
    projectId: 'auth-7b96d',
    authDomain: 'auth-7b96d.firebaseapp.com',
    storageBucket: 'auth-7b96d.appspot.com',
    measurementId: 'G-J2KRZ9M1NE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNkcAKMswmqFpC2mJ0LTEdQy6334a7NaQ',
    appId: '1:812438153804:android:4bca6e9312368789a822e9',
    messagingSenderId: '812438153804',
    projectId: 'auth-7b96d',
    storageBucket: 'auth-7b96d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8KLo3iW7dYWnTZhIU7rgLwD3Q7tXS1po',
    appId: '1:812438153804:ios:ed2b8956dae0b562a822e9',
    messagingSenderId: '812438153804',
    projectId: 'auth-7b96d',
    storageBucket: 'auth-7b96d.appspot.com',
    iosClientId: '812438153804-2sft59kjblb7rea3q0c7nlao3f72pbji.apps.googleusercontent.com',
    iosBundleId: 'com.example.autoUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8KLo3iW7dYWnTZhIU7rgLwD3Q7tXS1po',
    appId: '1:812438153804:ios:ed2b8956dae0b562a822e9',
    messagingSenderId: '812438153804',
    projectId: 'auth-7b96d',
    storageBucket: 'auth-7b96d.appspot.com',
    iosClientId: '812438153804-2sft59kjblb7rea3q0c7nlao3f72pbji.apps.googleusercontent.com',
    iosBundleId: 'com.example.autoUi',
  );
}
